---
title: "Influenza A Typing Report" 
date: "`r Sys.Date()`"
output: html_document
params:
  csv: ""
  
---
```{r setup, include=FALSE}
library(knitr)
library(base64enc)

```


<br>

Predicted using abricate tool with insaflu database as option. For more info please see https://github.com/tseemann/abricate and https://insaflu.insa.pt/

## Influenza A HA and NA Sequences {.tabset .tabset-pills}
```{r, results='asis',echo=FALSE}
samplelist <- read.csv(params$csv,header=FALSE,sep = ',')
sampleid <- samplelist[,c(1)]

for (i in sampleid){
  
  
  cat("###", i, "\n")
  
 
  insa_id <- (paste(i,"_insaflu_typing.csv",sep=""))
  abricate_raw1 <- read.csv(insa_id,header = TRUE,sep="\t")
  abricate_final1 <- abricate_raw1[,c(2,6,15,7,10,11,13,12)]
  colnames(abricate_final1) <- c("SAMPLE ID","GENE","TYPE","COVERAGE","%COVERAGE","%IDENTITY","MATCH","DATABASE")
  print(knitr::kable(abricate_final1,align = "llllcclr"))
  cat("\n")
  
  # Display fasta sequence
  fasta_id <- (paste(i,"_ORF.fasta",sep=""))
  fasta_file <- readLines(fasta_id)
  # Display the content
  cat("```\n")
  cat(fasta_file, sep = "\n")
  cat("\n```\n")
  # Encode the file content as base64
  encoded_content <- base64encode(charToRaw(paste(fasta_file, collapse = "\n")))
  # Get file name from file path and remove extra underscores
  file_name <- gsub("_+", "_", basename(fasta_id))
  # Provide a download link for the encoded FASTA content with file name
  cat('<a href="data:text/plain;charset=utf-8;base64,', encoded_content, '" download="', file_name, '">Download FASTA file</a>')
  
  cat('\n\n<!-- -->\n\n')
}
```
<br>
